# Generated by Django 2.0 on 2019-08-27 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='跟进日期')),
                ('content', models.TextField(verbose_name='跟进内容')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='客户姓名')),
                ('contact', models.CharField(help_text='电话/微信等', max_length=32, verbose_name='联系方式')),
                ('status', models.IntegerField(choices=[(1, '已签合同'), (2, '未签合同')], default=2, verbose_name='状态')),
                ('source', models.IntegerField(blank=True, choices=[(1, '官方网站'), (2, '销售宣传'), (3, '代理商')], null=True, verbose_name='销售渠道')),
                ('consultant_date', models.DateTimeField(blank=True, null=True, verbose_name='咨询日期')),
            ],
        ),
        migrations.CreateModel(
            name='DepartMent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='部门')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='产品数量')),
                ('check_date', models.DateTimeField(blank=True, null=True, verbose_name='订单审核')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='交货日期')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.IntegerField(choices=[(1, '定金'), (2, '尾款'), (3, '其它')], verbose_name='付款类型')),
                ('paid_fee', models.CharField(max_length=16, verbose_name='费用')),
                ('confirm_date', models.DateTimeField(blank=True, null=True, verbose_name='确认日期')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='生产流程名称')),
                ('status', models.IntegerField(choices=[(1, '未准备好'), (2, '已准备好')], default=2, verbose_name='生产流程状态')),
                ('reason', models.TextField(blank=True, help_text='如果该流程出现问题，请说明原因', null=True, verbose_name='原因')),
                ('product_status', models.IntegerField(choices=[(1, '未完成'), (2, '已完成')], default=1, verbose_name='产品完成状态')),
                ('scedule', models.TextField(blank=True, null=True, verbose_name='产品完成情况')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Order', verbose_name='订单')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Procedure', verbose_name='上一个流程')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='产品名称')),
                ('price', models.CharField(max_length=16, verbose_name='产品价格')),
                ('paramters', models.TextField(blank=True, null=True, verbose_name='产品参数')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '审核通过'), (2, '审核未通过')], default=2, verbose_name='审核状态')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='未通过原因')),
                ('audit_date', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Procedure', verbose_name='订单-产品信息')),
            ],
        ),
        migrations.CreateModel(
            name='ProductParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.TextField(blank=True, null=True, verbose_name='工艺参数')),
                ('quality', models.TextField(blank=True, null=True, verbose_name='品质参数')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Product', verbose_name='产品')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱')),
                ('name', models.CharField(max_length=32, verbose_name='真实姓名')),
                ('phone', models.CharField(max_length=32, verbose_name='手机号')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.DepartMent', verbose_name='所属部门')),
                ('roles', models.ManyToManyField(blank=True, to='rbac.Role', verbose_name='拥有的所有角色')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='WorkShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True, verbose_name='车间')),
            ],
        ),
        migrations.AddField(
            model_name='productparameter',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.WorkShop', verbose_name='车间'),
        ),
        migrations.AddField(
            model_name='productaudit',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to={'department__name': '总经理办'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.UserInfo', verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.WorkShop', verbose_name='生产车间'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='confirm_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'department__name': '财务部'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirms', to='crm.UserInfo', verbose_name='确认人'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Order', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='order',
            name='consultant',
            field=models.ForeignKey(blank=True, limit_choices_to={'department__name': '项目部'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.UserInfo', verbose_name='咨询顾问'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Product', verbose_name='购买的产品'),
        ),
        migrations.AddField(
            model_name='customer',
            name='consultant',
            field=models.ForeignKey(limit_choices_to={'department__name': '项目部'}, on_delete=django.db.models.deletion.CASCADE, to='crm.UserInfo', verbose_name='咨询顾问'),
        ),
        migrations.AddField(
            model_name='customer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Product', verbose_name='咨询的产品'),
        ),
        migrations.AddField(
            model_name='customer',
            name='referral_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='crm.Customer', verbose_name='自己内部顾客介绍'),
        ),
        migrations.AddField(
            model_name='consultantrecord',
            name='consultant',
            field=models.ForeignKey(limit_choices_to={'department__name': '项目部'}, on_delete=django.db.models.deletion.CASCADE, to='crm.UserInfo', verbose_name='跟进人'),
        ),
        migrations.AddField(
            model_name='consultantrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer', verbose_name='所咨询客户'),
        ),
    ]
