# Generated by Django 2.0 on 2019-08-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='roles', to='rbac.Role', verbose_name='拥有的所有角色'),
        ),
    ]
