# Generated by Django 2.0 on 2019-08-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20190827_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='level',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='权限等级'),
        ),
    ]
