# Generated by Django 2.0 on 2019-08-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_permission_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='level',
        ),
    ]
