# Generated by Django 2.0 on 2019-08-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_remove_permission_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='desc',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='角色描述'),
        ),
    ]
