"""
Django settings for yw_django_vue project.

Generated by 'django-admin startproject' using Django 1.11.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'q+p-6ub&5_#n38t%5m7avjb#l^aa0&*dg)3h!wzo&3dheuwn=7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',#放在新建应用之前
    'rest_framework',
    'django_filters',
    'rbac',
    'crm'
]

from django.contrib.sessions.middleware import SessionMiddleware

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # 注意顺序，放在此处
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'rbac.middleware.rbac.RbacMiddleware',
]
#设置session存储方式
#<django.contrib.sessions.backends.db.SessionStore object at 0x0000000005DC9748>
# SESSION_ENGINE='django.contrib.sessions.backends.cached_db'

CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True



ROOT_URLCONF = 'yw_django_vue.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'yw_django_vue.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'yw_django_vue',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

REST_FRAMEWORK = {
    # 'EXCEPTION_HANDLER': 'rbac.utils.custom_execption.custom_exception_handler',

    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',
                                'rest_framework.filters.SearchFilter',  # 搜索功能
                                'rest_framework.filters.OrderingFilter',  # 排序功能
                                ),

    # 全局使用的认证类
    "DEFAULT_AUTHENTICATION_CLASSES":['crm.utils.auth.AuthToken',],
    #全局权限类
    "DEFAULT_PERMISSION_CLASSES": ['rbac.permissions.Permission', ],
    # "UNAUTHENTICATED_USER":None, # 匿名，request.user = None
    # "UNAUTHENTICATED_TOKEN":None,# 匿名，request.auth = None


}



# 使用redis保存session数据
# SESSION_ENGINE = 'redis_sessions.session'
# SESSION_REDIS_HOST = '192.168.0.104'
# SESSION_REDIS_PORT = 6379
# SESSION_REDIS_DB = 4
# SESSION_REDIS_PASSWORD = 'bright123'
# SESSION_REDIS_PREFIX = 'session'

# SESSION_ENGINE = 'redis_sessions.session'
# SESSION_REDIS = {
#     'host': '192.168.0.104',
#     'port': 6379,
#     'db': 4,
#     'password': 'bright123',
#     'prefix': 'session',
#     'socket_timeout': 1
# }

# redis在django中的配置
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://192.168.0.104:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 100},
            "PASSWORD": "bright123",
        }
    }
}
# session的存储配置
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'

# 设置session失效时间,单位为秒
SESSION_COOKIE_AGE = 60*5

# USER_MODEL_PATH='crm.models.UserInfo'


# 无需权限控制的URL
RBAC_NO_AUTH_URL = [
    '/login',

]
PERMISSION_SESSION_KEY='permissions_dict'
MENU_SESSION_KEY='menus_dict'

#用户角色拥有的请求方式列表
PERMISSION_CODE_LIST_KEY = "permission_code_list"

#用户拥有的所有权限
USER_PERMISSION_DICT_KEY = "user_permission_dict"